### ISSUE TITLE
Can't login with fly

### ISSUE THREAD

**Issue by kondaurovDev** [concourse/concourse-docker#22]
I'm using this docker-compose file:
```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://192.168.99.100:8080
    - CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK
```

I can login via web UI. But when i try to login via concole i get this:

```
Aleksandrs-Mini:concourse aleksandr$ fly -t local login -c http://192.168.99.100:8080/
logging in to team 'main'

navigate to the following URL in your browser:

  http://192.168.99.100:8080/sky/login?redirect_uri=http://127.0.0.1:64552/auth/callback

or enter token manually: 
```

I navigate browser to that url and get this:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/concourse/fly/rc.SaveTarget(0x7ffeefbffbf7, 0x5, 0x7ffeefbffc06, 0x1a, 0xc420073900, 0x15b6074, 0x4, 0xc420195fe0, 0x0, 0x0, ...)
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/concourse/fly/rc/targets.go:86 +0x15a
github.com/concourse/fly/commands.(*LoginCommand).saveTarget(0x18a43c0, 0x7ffeefbffc06, 0x1a, 0xc420073b50, 0x0, 0x0, 0x2a4, 0x0)
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/concourse/fly/commands/login.go:266 +0xf3
github.com/concourse/fly/commands.(*LoginCommand).Execute(0x18a43c0, 0xc4200a8fa0, 0x0, 0x5, 0x18a43c0, 0x1)
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/concourse/fly/commands/login.go:130 +0x7a0
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42001ede0, 0xc42001e0d0, 0x5, 0x5, 0x14e8720, 0xc4201cd530, 0xc420073f28, 0x1485f1f, 0xc4201286c0)
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/jessevdk/go-flags.(*Parser).Parse(0xc42001ede0, 0x15b74fb, 0x8, 0xc420124780, 0x0, 0xc4200656e0)
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /Users/pilot/Worker/workdir/volumes/live/6eb60b0b-4163-4e0e-7da5-a3fa39959fa3/volume/concourse/src/github.com/concourse/fly/main.go:24 +0x10b
```

I just want to play with concourse but it is not so easy in latest version :(
