### ISSUE TITLE
set-team & set-pipeline fails with error: forbidden

### ISSUE THREAD

**Issue by robin-rpr** [concourse/concourse-docker#24]
* Concourse Version: 4.2.1
* Did this used to work? N/A

When i try to run my `setup.sh` (https://github.com/GONEproject/engine/tree/TASK/ISS%239/.ci) script already fails on the set-team job with `error: forbidden`.

> **Note:** When skipping the `set-team` command the script fails on the `set-pipeline` job with the same error =\

![Image of setup.sh output](https://i.imgur.com/OluhOgO.png)

Heres my `docker-compose.yml` on the serverside:
```yaml
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=1234
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse:4.2.1
    command: quickstart
    links: [concourse-db]
    depends_on: [concourse-db]
    privileged: true
    ports: ["3000:3000"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=1234
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_BIND_PORT=3000
    - CONCOURSE_EXTERNAL_URL=https://concourse.api-spot.com
    - CONCOURSE_ADD_LOCAL_USER=concourse:12345
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK

  concourse-worker:
    image: concourse/concourse:4.2.1
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
```

Thanks,
Robin Rpr.
