### ISSUE TITLE
Web not connecting to DB

### ISSUE THREAD

**Issue by downright77086** [concourse/concourse-docker#41]
I have followed instructions about running ssh key gen script, then run docker-compose.
Here is what I see when doing that.

```
Attaching to concourse_concourse-db_1, concourse_concourse-web_1, concourse_concourse-worker_1
concourse-web_1     | {"timestamp":"2019-04-06T21:01:50.941371647Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
concourse-web_1     | {"timestamp":"2019-04-06T21:01:50.945134121Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 172.20.0.2:5432: connect: connection refused","session":"3"}}
concourse-db_1      | The files belonging to this database system will be owned by user "postgres".
concourse-db_1      | This user must also own the server process.
```

Here is my compose file just trying to run some testing 

```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=password123
    - POSTGRES_USER=concourse
    - PGDATA=/database

  concourse-web:
    image: concourse/concourse
    command: web
    links: [concourse-db]
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse
    - CONCOURSE_POSTGRES_PASSWORD=password123
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://server-ipaddress:8080
    - CONCOURSE_ADD_LOCAL_USER=test:test
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=test

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK
```
