### ISSUE TITLE
Docker container dies at latest version, and at 5.0.1

### ISSUE THREAD

**Issue by iamrenejr** [concourse/concourse-docker#45]
Following the instructions here:

https://concourse-ci.org/install.html

Leads to the docker instance running concourse to simply die. There is no error message that `docker-compose logs -f` gives (only the postgres server logs anything), the container simply cannot run, even if I manually try to do `docker run -d -p 8080:8080 <image_name>`

I've downgraded to v5.0.1, and the same issue happens.

Downgrading to v5.0.0 fixes the issue. This is the working docker-compose.yml file (the change from the default is me explicitly putting the version number):

```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:5.0.0
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
```

I'm running on an AWS `t2.large` instance with 19G free disk space.
